---
- name: Install parted package
  ansible.builtin.apt:
    name: parted
    state: present
    update_cache: yes
  become: yes

- name: Create partition on data disk
  ansible.builtin.command: parted -s /dev/sdc mklabel gpt mkpart primary ext4 0% 100%
  become: yes
  args:
    creates: /dev/sdc1

- name: Format partition as ext4
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdc1
  become: yes

- name: Create mount point
  ansible.builtin.file:
    path: /mnt/data
    state: directory
    mode: '0755'
  become: yes

- name: Mount data disk
  ansible.builtin.mount:
    path: /mnt/data
    src: /dev/sdc1
    fstype: ext4
    state: mounted
  become: yes
