---
- name: Create partitions on data disk
  ansible.builtin.parted:
    device: "{{ disk_device }}"
    number: "{{ item.number }}"
    part_end: "{{ item.size }}"
    state: present
  loop: "{{ partitions }}"

- name: Format partitions
  ansible.builtin.filesystem:
    fstype: "{{ item.filesystem }}"
    dev: "{{ disk_device }}{{ item.number }}"
  loop: "{{ partitions }}"

- name: Create mount points
  ansible.builtin.file:
    path: "{{ item.mount_point }}"
    state: directory
  loop: "{{ partitions }}"

- name: Mount partitions
  ansible.builtin.mount:
    path: "{{ item.mount_point }}"
    src: "{{ disk_device }}{{ item.number }}"
    fstype: "{{ item.filesystem }}"
    state: mounted
  loop: "{{ partitions }}"
