---
- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
  become: yes

- name: Copy HTML file for specific VM
  ansible.builtin.copy:
    src: "{{ inventory_hostname }}.html"
    dest: /var/www/html/index.html
    mode: '0644'
  become: yes
  notify: Restart Apache

- name: Ensure Apache is running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  become: yes
