---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present

- name: Copy index.html to respective VM
  ansible.builtin.copy:
    src: "{{ web_files[inventory_hostname].file }}"
    dest: /var/www/html/index.html
    mode: '0444'
  notify: Restart Apache

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Create user100
  ansible.builtin.user:
    name: user100
    state: present
    groups: sudo
    append: yes

- name: Set up SSH key for user100
  ansible.builtin.authorized_key:
    user: user100
    state: present
    key: "{{ lookup('file', '/home/n01736553/.ssh/user100_id_rsa.pub') }}"---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present

- name: Copy index.html to respective VM
  ansible.builtin.copy:
    src: "{{ web_files[inventory_hostname].file }}"
    dest: /var/www/html/index.html
    mode: '0444'
  notify: Restart Apache

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Create user100
  ansible.builtin.user:
    name: user100
    state: present
    groups: sudo
    append: yes

- name: Set up SSH key for user100
  ansible.builtin.authorized_key:
    user: user100
    state: present
    key: "{{ lookup('file', '/home/n01736553/.ssh/user100_id_rsa.pub') }}"
