---
- name: Install Apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: Copy index.html to respective VM
  ansible.builtin.copy:
    src: "{{ web_files[inventory_hostname].file }}"
    dest: /var/www/html/index.html
    mode: '0444'
  notify: Restart Apache

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
