---
linux_vms:
  hosts:
    vm1:
      ansible_host: lb6553.canadacentral.cloudapp.azure.com
      ansible_user: adminuser
      ansible_port: 2200
    vm2:
      ansible_host: lb6553.canadacentral.cloudapp.azure.com
      ansible_user: adminuser
      ansible_port: 2201
    vm3:
      ansible_host: lb6553.canadacentral.cloudapp.azure.com
      ansible_user: adminuser
      ansible_port: 2202
