---
- name: Create student user
  ansible.builtin.user:
    name: "{{ student_username }}"
    password: "{{ student_password | password_hash('sha512') }}"
    shell: /bin/bash
    state: present
  become: yes

- name: Create .ssh directory for student
  ansible.builtin.file:
    path: "/home/{{ student_username }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ student_username }}"
    group: "{{ student_username }}"
  become: yes

- name: Copy SSH public key for student
  ansible.builtin.copy:
    src: "{{ ssh_public_key_path }}"
    dest: "/home/{{ student_username }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ student_username }}"
    group: "{{ student_username }}"
  become: yes
